//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NinimumWarehouse.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NinimumWarehouse.Resources.Languages.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action failed. Refresh and try again..
        /// </summary>
        public static string ActionFailed {
            get {
                return ResourceManager.GetString("ActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another worker is preparing this order. Refresh the list..
        /// </summary>
        public static string AlreadyClaimed {
            get {
                return ResourceManager.GetString("AlreadyClaimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NinimumStock.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode does not match this product..
        /// </summary>
        public static string BarcodeMismatch {
            get {
                return ResourceManager.GetString("BarcodeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode on the package.
        /// </summary>
        public static string BarcodePlaceholder {
            get {
                return ResourceManager.GetString("BarcodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the barcode on the package..
        /// </summary>
        public static string BarcodeRequired {
            get {
                return ResourceManager.GetString("BarcodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem reported.
        /// </summary>
        public static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow camera access in phone settings or enter the barcode..
        /// </summary>
        public static string CameraPermission {
            get {
                return ResourceManager.GetString("CameraPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        public static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total checked quantity.
        /// </summary>
        public static string CheckedQuantity {
            get {
                return ResourceManager.GetString("CheckedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check barcode.
        /// </summary>
        public static string ConfirmCode {
            get {
                return ResourceManager.GetString("ConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm manually.
        /// </summary>
        public static string ConfirmManually {
            get {
                return ResourceManager.GetString("ConfirmManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not reach the server. Check your connection and refresh..
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders you mark ready will appear here..
        /// </summary>
        public static string EmptyHistoryMessage {
            get {
                return ResourceManager.GetString("EmptyHistoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History is empty.
        /// </summary>
        public static string EmptyHistoryTitle {
            get {
                return ResourceManager.GetString("EmptyHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an order from the queue to get started..
        /// </summary>
        public static string EmptyMineMessage {
            get {
                return ResourceManager.GetString("EmptyMineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No orders in progress.
        /// </summary>
        public static string EmptyMineTitle {
            get {
                return ResourceManager.GetString("EmptyMineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New paid orders will appear here..
        /// </summary>
        public static string EmptyQueueMessage {
            get {
                return ResourceManager.GetString("EmptyQueueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No orders yet.
        /// </summary>
        public static string EmptyQueueTitle {
            get {
                return ResourceManager.GetString("EmptyQueueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter barcode manually.
        /// </summary>
        public static string EnterCodeInstead {
            get {
                return ResourceManager.GetString("EnterCodeInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your checked and packed orders..
        /// </summary>
        public static string HistorySubtitle {
            get {
                return ResourceManager.GetString("HistorySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some products have not been checked. Scan each product or enter its barcode and confirm the quantity. For products without a barcode, enter a reason and confirm manually. Only then mark the order as packed and ready..
        /// </summary>
        public static string Incomplete {
            get {
                return ResourceManager.GetString("Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the details. Quantity must be a positive whole number..
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order status has changed. Refresh the page..
        /// </summary>
        public static string InvalidState {
            get {
                return ResourceManager.GetString("InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check products.
        /// </summary>
        public static string ItemsTitle {
            get {
                return ResourceManager.GetString("ItemsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageEn {
            get {
                return ResourceManager.GetString("LanguageEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string LanguageRu {
            get {
                return ResourceManager.GetString("LanguageRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O‘zbekcha.
        /// </summary>
        public static string LanguageUz {
            get {
                return ResourceManager.GetString("LanguageUz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading….
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect login or password..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the login and password provided by your administrator..
        /// </summary>
        public static string LoginHint {
            get {
                return ResourceManager.GetString("LoginHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your login and password..
        /// </summary>
        public static string LoginRequired {
            get {
                return ResourceManager.GetString("LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare warehouse orders in one place.
        /// </summary>
        public static string LoginSubtitle {
            get {
                return ResourceManager.GetString("LoginSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No barcode is available. Check the product and record a reason..
        /// </summary>
        public static string ManualCheckHint {
            get {
                return ResourceManager.GetString("ManualCheckHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My orders.
        /// </summary>
        public static string MyOrders {
            get {
                return ResourceManager.GetString("MyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your orders in preparation are here..
        /// </summary>
        public static string MyOrdersSubtitle {
            get {
                return ResourceManager.GetString("MyOrdersSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No barcode.
        /// </summary>
        public static string NoBarcode {
            get {
                return ResourceManager.GetString("NoBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open order.
        /// </summary>
        public static string OpenOrder {
            get {
                return ResourceManager.GetString("OpenOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order is no longer awaiting preparation. Its payment or delivery status has changed..
        /// </summary>
        public static string OrderUnavailable {
            get {
                return ResourceManager.GetString("OrderUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another worker is preparing this order..
        /// </summary>
        public static string OtherWorker {
            get {
                return ResourceManager.GetString("OtherWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packed — ready.
        /// </summary>
        public static string PackedReady {
            get {
                return ResourceManager.GetString("PackedReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check every product, then pack the order..
        /// </summary>
        public static string PackingHint {
            get {
                return ResourceManager.GetString("PackingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}.
        /// </summary>
        public static string PageFormat {
            get {
                return ResourceManager.GetString("PageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing.
        /// </summary>
        public static string Picking {
            get {
                return ResourceManager.GetString("Picking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait….
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The warehouse app is not enabled yet. Contact your administrator..
        /// </summary>
        public static string PreparationDisabled {
            get {
                return ResourceManager.GetString("PreparationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem.
        /// </summary>
        public static string Problem {
            get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve the problem before marking the order ready..
        /// </summary>
        public static string ProblemHint {
            get {
                return ResourceManager.GetString("ProblemHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe the problem.
        /// </summary>
        public static string ProblemPrompt {
            get {
                return ResourceManager.GetString("ProblemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}.
        /// </summary>
        public static string ProductProgressFormat {
            get {
                return ResourceManager.GetString("ProductProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All order actions are recorded under your account..
        /// </summary>
        public static string ProfileHint {
            get {
                return ResourceManager.GetString("ProfileHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1} units checked.
        /// </summary>
        public static string ProgressFormat {
            get {
                return ResourceManager.GetString("ProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} product units.
        /// </summary>
        public static string QuantityFormat {
            get {
                return ResourceManager.GetString("QuantityFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count the products you have and enter the total..
        /// </summary>
        public static string QuantityHelp {
            get {
                return ResourceManager.GetString("QuantityHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a whole number greater than zero for the checked quantity..
        /// </summary>
        public static string QuantityInvalid {
            get {
                return ResourceManager.GetString("QuantityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an order to start preparing..
        /// </summary>
        public static string QueueSubtitle {
            get {
                return ResourceManager.GetString("QueueSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm all items are checked and packed..
        /// </summary>
        public static string ReadyConfirmation {
            get {
                return ResourceManager.GetString("ReadyConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order is ready for a courier..
        /// </summary>
        public static string ReadyMessage {
            get {
                return ResourceManager.GetString("ReadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the order ready?.
        /// </summary>
        public static string ReadyQuestion {
            get {
                return ResourceManager.GetString("ReadyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, the package has no barcode.
        /// </summary>
        public static string ReasonPlaceholder {
            get {
                return ResourceManager.GetString("ReasonPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a reason for manual confirmation..
        /// </summary>
        public static string ReasonRequired {
            get {
                return ResourceManager.GetString("ReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a problem.
        /// </summary>
        public static string ReportProblem {
            get {
                return ResourceManager.GetString("ReportProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem resolved — continue.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking returned products.
        /// </summary>
        public static string ReturnChecking {
            get {
                return ResourceManager.GetString("ReturnChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm that all checked products are physically in the warehouse, undamaged and suitable for sale. Stock will be restored once. Payment refunds are handled separately..
        /// </summary>
        public static string ReturnConfirmation {
            get {
                return ResourceManager.GetString("ReturnConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received by warehouse.
        /// </summary>
        public static string Returned {
            get {
                return ResourceManager.GetString("Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No returns awaiting receipt..
        /// </summary>
        public static string ReturnEmpty {
            get {
                return ResourceManager.GetString("ReturnEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check all products physically received. Confirm only complete, undamaged products suitable for sale..
        /// </summary>
        public static string ReturnHint {
            get {
                return ResourceManager.GetString("ReturnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive returned products?.
        /// </summary>
        public static string ReturnQuestion {
            get {
                return ResourceManager.GetString("ReturnQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received — restore stock.
        /// </summary>
        public static string ReturnReceive {
            get {
                return ResourceManager.GetString("ReturnReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned products received and checked..
        /// </summary>
        public static string ReturnReceivedMessage {
            get {
                return ResourceManager.GetString("ReturnReceivedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns.
        /// </summary>
        public static string Returns {
            get {
                return ResourceManager.GetString("Returns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check returned products.
        /// </summary>
        public static string ReturnStart {
            get {
                return ResourceManager.GetString("ReturnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting warehouse receipt.
        /// </summary>
        public static string ReturnWaiting {
            get {
                return ResourceManager.GetString("ReturnWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point the camera at the barcode on the package..
        /// </summary>
        public static string ScanHint {
            get {
                return ResourceManager.GetString("ScanHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan barcode.
        /// </summary>
        public static string ScanTitle {
            get {
                return ResourceManager.GetString("ScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan and check.
        /// </summary>
        public static string ScanToCheck {
            get {
                return ResourceManager.GetString("ScanToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was opened on another device or the session expired. Sign in again..
        /// </summary>
        public static string SessionEnded {
            get {
                return ResourceManager.GetString("SessionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in again.
        /// </summary>
        public static string SignInAgain {
            get {
                return ResourceManager.GetString("SignInAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need your login and password to sign in again..
        /// </summary>
        public static string SignOutMessage {
            get {
                return ResourceManager.GetString("SignOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out of your account?.
        /// </summary>
        public static string SignOutQuestion {
            get {
                return ResourceManager.GetString("SignOutQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account can be used on one device at a time..
        /// </summary>
        public static string SingleSessionHint {
            get {
                return ResourceManager.GetString("SingleSessionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start preparing.
        /// </summary>
        public static string StartPreparing {
            get {
                return ResourceManager.GetString("StartPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To check.
        /// </summary>
        public static string ToCheck {
            get {
                return ResourceManager.GetString("ToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity cannot exceed the ordered amount..
        /// </summary>
        public static string TooMany {
            get {
                return ResourceManager.GetString("TooMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on torch.
        /// </summary>
        public static string Torch {
            get {
                return ResourceManager.GetString("Torch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off torch.
        /// </summary>
        public static string TorchOff {
            get {
                return ResourceManager.GetString("TorchOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}.
        /// </summary>
        public static string TotalFormat {
            get {
                return ResourceManager.GetString("TotalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order was cancelled, refunded, or handed to a courier..
        /// </summary>
        public static string UnavailableError {
            get {
                return ResourceManager.GetString("UnavailableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status updated.
        /// </summary>
        public static string UnknownStatus {
            get {
                return ResourceManager.GetString("UnknownStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse worker.
        /// </summary>
        public static string Worker {
            get {
                return ResourceManager.GetString("Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker login.
        /// </summary>
        public static string WorkerId {
            get {
                return ResourceManager.GetString("WorkerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, ready.
        /// </summary>
        public static string YesReady {
            get {
                return ResourceManager.GetString("YesReady", resourceCulture);
            }
        }
    }
}
